### ISSUE TITLE
Fix ssl error on  Alpine 3.4

### ISSUE THREAD

**Issue by chusiang** [chusiang/ansible-jupyter.dockerfile#13]
I get the ssl error when install the Ansible 2.3.1 on Alpine linux 3.4.

> https://hub.docker.com/r/chusiang/ansible-jupyter/builds/bcfwzvzefujyrau3h6mvhcf/

```
...
Step 6/14 : RUN pip install ansible

 ---> Running in 2b95aafd3a08

Collecting ansible

  Downloading ansible-2.3.1.0.tar.gz (4.3MB)

Collecting jinja2 (from ansible)

  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)

Collecting PyYAML (from ansible)

  Downloading PyYAML-3.12.tar.gz (253kB)

Collecting paramiko (from ansible)

  Downloading paramiko-2.2.1-py2.py3-none-any.whl (176kB)

Collecting pycrypto>=2.6 (from ansible)

  Downloading pycrypto-2.6.1.tar.gz (446kB)

Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from ansible)

Collecting MarkupSafe>=0.23 (from jinja2->ansible)

  Downloading MarkupSafe-1.0.tar.gz

Collecting cryptography>=1.1 (from paramiko->ansible)

  Downloading cryptography-1.9.tar.gz (409kB)

Collecting bcrypt>=3.1.3 (from paramiko->ansible)

  Downloading bcrypt-3.1.3.tar.gz (40kB)

Collecting pyasn1>=0.1.7 (from paramiko->ansible)

  Downloading pyasn1-0.2.3-py2.py3-none-any.whl (53kB)

Collecting pynacl>=1.0.1 (from paramiko->ansible)

  Downloading PyNaCl-1.1.2.tar.gz (3.1MB)

    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/cffi/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'cffi' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for cffi>=1.4.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4LaWvQ/pynacl/setup.py", line 232, in <module>
        "Programming Language :: Python :: 3.6",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 634, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.4.1')
    
    ----------------------------------------

[91mCommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4LaWvQ/pynacl/
[0m
Removing intermediate container 2b95aafd3a08

The command '/bin/sh -c pip install ansible' returned a non-zero code: 1
```

**Comment by chusiang** [comment]
It has be fixed after I install more package of `ca-certificates`.
