### ISSUE TITLE
Fix the `ubuntu-14.04` image build fail

### ISSUE THREAD

**Issue by chusiang** [chusiang/ansible-jupyter.dockerfile#7]
於 2017/02/28 06:58 收到 Docker Hub 的 build fail 通知。

- OS: Ubuntu 14.04
- Build Code: [bbmjuyb8hbgqlhcxfg3et2x](https://hub.docker.com/r/chusiang/ansible-jupyter/builds/bbmjuyb8hbgqlhcxfg3et2x/), [bjgkvpwtgagv9ffqrxdpav9](https://hub.docker.com/r/chusiang/ansible-jupyter/builds/bjgkvpwtgagv9ffqrxdpav9/)
- Error log:

  ```
  TASK [install the jupyter notebook] ********************************************
  task path: /home/setup_jupyter.yml:130
  Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/packaging/language/pip.py
  <localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
  <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488320769.37-160308117687180 `" && echo ansible-tmp-1488320769.37-160308117687180="` echo ~/.ansible/tmp/ansible-tmp-1488320769.37-160308117687180 `" ) && sleep 0'
  <localhost> PUT /tmp/tmpB3mg3V TO /root/.ansible/tmp/ansible-tmp-1488320769.37-160308117687180/pip.py
  <localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1488320769.37-160308117687180/ /root/.ansible/tmp/ansible-tmp-1488320769.37-160308117687180/pip.py && sleep 0'
  <localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1488320769.37-160308117687180/pip.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1488320769.37-160308117687180/" > /dev/null 2>&1 && sleep 0'
  fatal: [localhost]: FAILED! => {
      "changed": false, 
      "cmd": "/usr/local/bin/pip2 install jupyter==1.0.0", 
      "failed": true, 
      "invocation": {
          "module_args": {
              "chdir": null, 
              "editable": true, 
              "executable": null, 
              "extra_args": null, 
              "name": [
                  "jupyter"
              ], 
              "requirements": null, 
              "state": "present", 
              "umask": null, 
              "use_mirrors": true, 
              "version": "1.0.0", 
              "virtualenv": null, 
              "virtualenv_command": "virtualenv", 
              "virtualenv_python": null, 
              "virtualenv_site_packages": false
          }, 
          "module_name": "pip"
      }, 
      "msg": "stdout: Collecting jupyter==1.0.0\n  Downloading jupyter-1.0.0-py2.py3-none-any.whl\nCollecting nbconvert (from jupyter==1.0.0)\n  Downloading nbconvert-5.1.1-py2.py3-none-any.whl (372kB)\nCollecting ipykernel (from jupyter==1.0.0)\n  Downloading ipykernel-4.5.2-py2.py3-none-any.whl (98kB)\nCollecting jupyter-console (from jupyter==1.0.0)\n  Downloading jupyter_console-5.1.0-py2.py3-none-any.whl\nCollecting qtconsole (from jupyter==1.0.0)\n  Downloading qtconsole-4.2.1-py2.py3-none-any.whl (104kB)\nCollecting notebook (from jupyter==1.0.0)\n  Downloading notebook-4.4.1-py2.py3-none-any.whl (6.9MB)\nCollecting ipywidgets (from jupyter==1.0.0)\n  Downloading ipywidgets-6.0.0-py2.py3-none-any.whl (46kB)\nCollecting testpath (from nbconvert->jupyter==1.0.0)\n  Downloading testpath-0.3-py2.py3-none-any.whl (82kB)\nCollecting nbformat (from nbconvert->jupyter==1.0.0)\n  Downloading nbformat-4.3.0-py2.py3-none-any.whl (154kB)\nRequirement already satisfied: jinja2 in /usr/lib/python2.7/dist-packages (from nbconvert->jupyter==1.0.0)\nCollecting entrypoints>=0.2.2 (from nbconvert->jupyter==1.0.0)\n  Downloading entrypoints-0.2.2-py2.py3-none-any.whl\nCollecting pandocfilters>=1.4.1 (from nbconvert->jupyter==1.0.0)\n  Downloading pandocfilters-1.4.1.tar.gz\nCollecting jupyter-core (from nbconvert->jupyter==1.0.0)\n  Downloading jupyter_core-4.3.0-py2.py3-none-any.whl (76kB)\nCollecting traitlets>=4.2 (from nbconvert->jupyter==1.0.0)\n  Downloading traitlets-4.3.2-py2.py3-none-any.whl (74kB)\nCollecting bleach (from nbconvert->jupyter==1.0.0)\n  Downloading bleach-1.5.0-py2.py3-none-any.whl\nCollecting pygments (from nbconvert->jupyter==1.0.0)\n  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)\nCollecting mistune!=0.6 (from nbconvert->jupyter==1.0.0)\n  Downloading mistune-0.7.3-py2.py3-none-any.whl\nCollecting ipython>=4.0.0 (from ipykernel->jupyter==1.0.0)\n  Downloading ipython-5.3.0-py2-none-any.whl (750kB)\nCollecting tornado>=4.0 (from ipykernel->jupyter==1.0.0)\n  Downloading tornado-4.4.2.tar.gz (460kB)\nCollecting jupyter-client (from ipykernel->jupyter==1.0.0)\n  Downloading jupyter_client-5.0.0-py2.py3-none-any.whl (83kB)\nCollecting prompt-toolkit<2.0.0,>=1.0.0 (from jupyter-console->jupyter==1.0.0)\n  Downloading prompt_toolkit-1.0.13-py2-none-any.whl (247kB)\nCollecting terminado>=0.3.3; sys_platform != \"win32\" (from notebook->jupyter==1.0.0)\n  Downloading terminado-0.6.tar.gz\nCollecting ipython-genutils (from notebook->jupyter==1.0.0)\n  Downloading ipython_genutils-0.1.0-py2.py3-none-any.whl\nCollecting widgetsnbextension~=2.0.0 (from ipywidgets->jupyter==1.0.0)\n  Downloading widgetsnbextension-2.0.0-py2.py3-none-any.whl (1.1MB)\nRequirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python2.7/dist-packages (from nbformat->nbconvert->jupyter==1.0.0)\nRequirement already satisfied: markupsafe in /usr/lib/python2.7/dist-packages (from jinja2->nbconvert->jupyter==1.0.0)\nCollecting configparser>=3.5; python_version == \"2.7\" (from entrypoints>=0.2.2->nbconvert->jupyter==1.0.0)\n  Downloading configparser-3.5.0.tar.gz\nRequirement already satisfied: enum34; python_version == \"2.7\" in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.2->nbconvert->jupyter==1.0.0)\nRequirement already satisfied: six in /usr/lib/python2.7/dist-packages (from traitlets>=4.2->nbconvert->jupyter==1.0.0)\nCollecting decorator (from traitlets>=4.2->nbconvert->jupyter==1.0.0)\n  Downloading decorator-4.0.11-py2.py3-none-any.whl\nRequirement already satisfied: html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 in /usr/lib/python2.7/dist-packages (from bleach->nbconvert->jupyter==1.0.0)\nCollecting backports.shutil-get-terminal-size; python_version == \"2.7\" (from ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl\nCollecting setuptools>=18.5 (from ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading setuptools-34.3.0-py2.py3-none-any.whl (389kB)\nCollecting pickleshare (from ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading pickleshare-0.7.4-py2.py3-none-any.whl\nCollecting simplegeneric>0.8 (from ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading simplegeneric-0.8.1.zip\nCollecting pexpect; sys_platform != \"win32\" (from ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading pexpect-4.2.1-py2.py3-none-any.whl (55kB)\nCollecting pathlib2; python_version == \"2.7\" or python_version == \"3.3\" (from ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading pathlib2-2.2.1-py2.py3-none-any.whl\nRequirement already satisfied: backports.ssl_match_hostname in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel->jupyter==1.0.0)\nCollecting singledispatch (from tornado>=4.0->ipykernel->jupyter==1.0.0)\n  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl\nCollecting certifi (from tornado>=4.0->ipykernel->jupyter==1.0.0)\n  Downloading certifi-2017.1.23-py2.py3-none-any.whl (382kB)\nCollecting backports_abc>=0.4 (from tornado>=4.0->ipykernel->jupyter==1.0.0)\n  Downloading backports_abc-0.5-py2.py3-none-any.whl\nCollecting python-dateutil>=2.1 (from jupyter-client->ipykernel->jupyter==1.0.0)\n  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)\nCollecting pyzmq>=13 (from jupyter-client->ipykernel->jupyter==1.0.0)\n  Downloading pyzmq-16.0.2-cp27-cp27mu-manylinux1_x86_64.whl (3.0MB)\nCollecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.0->jupyter-console->jupyter==1.0.0)\n  Downloading wcwidth-0.1.7-py2.py3-none-any.whl\nCollecting ptyprocess (from terminado>=0.3.3; sys_platform != \"win32\"->notebook->jupyter==1.0.0)\n  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl\nRequirement already satisfied: functools32; python_version == \"2.7\" in /usr/local/lib/python2.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat->nbconvert->jupyter==1.0.0)\nCollecting appdirs>=1.4.0 (from setuptools>=18.5->ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading appdirs-1.4.2-py2.py3-none-any.whl\nCollecting packaging>=16.8 (from setuptools>=18.5->ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading packaging-16.8-py2.py3-none-any.whl\nCollecting scandir; python_version < \"3.5\" (from pathlib2; python_version == \"2.7\" or python_version == \"3.3\"->ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading scandir-1.5.tar.gz\nCollecting pyparsing (from packaging>=16.8->setuptools>=18.5->ipython>=4.0.0->ipykernel->jupyter==1.0.0)\n  Downloading pyparsing-2.1.10-py2.py3-none-any.whl (56kB)\nInstalling collected packages: testpath, decorator, ipython-genutils, traitlets, jupyter-core, nbformat, configparser, entrypoints, pandocfilters, bleach, pygments, mistune, nbconvert, backports.shutil-get-terminal-size, appdirs, pyparsing, packaging, setuptools, wcwidth, prompt-toolkit, scandir, pathlib2, pickleshare, simplegeneric, ptyprocess, pexpect, ipython, singledispatch, certifi, backports-abc, tornado, python-dateutil, pyzmq, jupyter-client, ipykernel, jupyter-console, qtconsole, terminado, notebook, widgetsnbextension, ipywidgets, jupyter\n  Running setup.py install for configparser: started\n    Running setup.py install for configparser: finished with status 'done'\n  Running setup.py install for pandocfilters: started\n    Running setup.py install for pandocfilters: finished with status 'done'\n  Found existing installation: setuptools 3.3\n    Uninstalling setuptools-3.3:\n      Successfully uninstalled setuptools-3.3\n  Running setup.py install for scandir: started\n    Running setup.py install for scandir: finished with status 'error'\n    Complete output from command /usr/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-VMBiQW/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-txYZqx-record/install-record.txt --single-version-externally-managed --compile:\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/tmp/pip-build-VMBiQW/scandir/setup.py\", line 54, in <module>\n        'Programming Language :: Python :: Implementation :: CPython',\n      File \"/usr/lib/python2.7/distutils/core.py\", line 111, in setup\n        _setup_distribution = dist = klass(attrs)\n      File \"/usr/local/lib/python2.7/dist-packages/setuptools/dist.py\", line 320, in __init__\n        _Distribution.__init__(self, attrs)\n      File \"/usr/lib/python2.7/distutils/dist.py\", line 287, in __init__\n        self.finalize_options()\n      File \"/usr/local/lib/python2.7/dist-packages/setuptools/dist.py\", line 386, in finalize_options\n        ep.require(installer=self.fetch_build_egg)\n      File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2324, in require\n        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n      File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 859, in resolve\n        raise VersionConflict(dist, req).with_context(dependent_req)\n    pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.6.0'))\n    \n    ----------------------------------------\n\n:stderr: /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.\n  SNIMissingWarning\n/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.\n  InsecurePlatformWarning\nCommand \"/usr/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-VMBiQW/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-txYZqx-record/install-record.txt --single-version-externally-managed --compile\" failed with error code 1 in /tmp/pip-build-VMBiQW/scandir/\n"
  }
  	to retry, use: --limit @/home/setup_jupyter.retry
  
  PLAY RECAP *********************************************************************
  localhost                  : ok=4    changed=3    unreachable=0    failed=1
  ```

**Comment by chusiang** [comment]
## bug fix

手動於 docker 跑安裝 jupyter 出現的 error message。

```
root@614d536c81f2:/home#  pip2 install jupyter==1.0.0
...
Collecting ipython>=4.0.0 (from ipykernel->jupyter==1.0.0)
  Using cached ipython-5.3.0-py2-none-any.whl
Collecting tornado>=4.0 (from ipykernel->jupyter==1.0.0)
  Using cached tornado-4.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ZYR58s/tornado/setup.py", line 184, in <module>
        **kwargs
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.6.0'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ZYR58s/tornado/
```

參照 [\[SOLVED\] Error while installing Flexget, Ubuntu Server Trusty \- help \- Forum \- FlexGet](https://discuss.flexget.com/t/solved-error-while-installing-flexget-ubuntu-server-trusty/1109) 一文，先使用 pip 升級 six，即可使用 pip 正常安裝 jupyter。

```
root@614d536c81f2:/home# pip install --upgrade six
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting six
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six
  Found existing installation: six 1.5.2
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.5.2:
      Successfully uninstalled six-1.5.2
Successfully installed six-1.10.0
```

成功安裝 jupyter。

```
root@614d536c81f2:/home# pip install jupter==1.0.0
...
Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging>=16.8->setuptools>=18.5->ipython>=4.0.0->ipykernel->jupyter==1.0.0)
Installing collected packages: scandir, pathlib2, pickleshare, simplegeneric, ptyprocess, pexpect, ipython, singledispatch, certifi, backports-abc, tornado, python-dateutil, pyzmq, jupyter-client, ipykernel, jupyter-console, qtconsole, terminado, notebook, widgetsnbextension, ipywidgets, jupyter
  Running setup.py install for scandir ... done
  Running setup.py install for simplegeneric ... done
  Running setup.py install for tornado ... done
  Running setup.py install for terminado ... done
Successfully installed backports-abc-0.5 certifi-2017.1.23 ipykernel-4.5.2 ipython-5.3.0 ipywidgets-6.0.0 jupyter-1.0.0 jupyter-client-5.0.0 jupyter-console-5.1.0 notebook-4.4.1 pathlib2-2.2.1 pexpect-4.2.1 pickleshare-0.7.4 ptyprocess-0.5.1 python-dateutil-2.6.0 pyzmq-16.0.2 qtconsole-4.2.1 scandir-1.5 simplegeneric-0.8.1 singledispatch-3.4.0.3 terminado-0.6 tornado-4.4.2 widgetsnbextension-2.0.0
```

**Comment by chusiang** [comment]
## Docker Hub

已將升級 six 的 task commit 至 GitHub 的 master，晚點睡起來再來 
https://hub.docker.com/r/chusiang/ansible-jupyter/builds/ 觀看建置結果了。

**Comment by chusiang** [comment]
2017.03.01 15:04 查看的結果為建置成功，且除了 `ubuntu-14.04` 外皆無 fail！
